spring:
  application:
    name: billing
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: false
    locations: classpath:db/migration
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

algashop:
  integrations:
    payment:
      provider: FASTPAY #FAKE
      fastpay:
        hostname: http://localhost:8087
        private-token: SSEewtC6Ps5yJLdB6SJmh1bqJXgRbCdf8ocDj2hU
        webhook-url: http://host.docker.internal:8082/api/v1/webhooks/fastpay

resilience4j:
  retry:
    instances:
      fastpayPayment:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.ErrorResponseException
        ignoreExceptions:
          - com.eskcti.algashop.billing.presentation.BadGatewayException
          - com.eskcti.algashop.billing.presentation.GatewayTimeoutException
          - org.springframework.web.client.HttpClientErrorException$NotFound
  circuitbreaker:
    instances:
      fastpayPayment:
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        recordExceptions:
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.ErrorResponseException
          - java.io.IOException
        ignoreExceptions:
          - com.eskcti.algashop.billing.presentation.BadGatewayException
          - com.eskcti.algashop.billing.presentation.GatewayTimeoutException
          - org.springframework.web.client.HttpClientErrorException$NotFound
  bulkhead:
    instances:
      fastpayPayment:
        maxConcurrentCalls: 25
        maxWaitDuration: 0

management:
  info:
    env.enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: db,readinessState
      status:
        order: "DOWN, OUT_OF_SERVICE, UNKNOWN, DEGRADED, UP"

info:
  app.name: AlgaShop Billing API
